import Product from "../product/Product";

const products: Product[] = [
  {
    id: 1,
    name: "Notebook Gamer Acer Nitro 5",
    description:
      "O Acer Nitro 5 é um notebook gamer poderoso, ideal para jogos pesados e multitarefas.",
    brand: "Acer",
    model: "AN515-54-58CL",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Facer-nitro-5.png?alt=media&token=094ba6a8-1a4d-414a-b32c-c176bfeaca8e",
    videoReview:
      "https://www.youtube.com/embed/8NQFr9De3lU?si=s_lN2KTQresD-36Y",
    rate: 4.5,
    tags: ["Baixou"],
    basePrice: 6499.99,
    promotionPrice: 5999.99,
    smallPrice: 4850.9,
    mediumPrice: 6503.7,
    largePrice: 9800.8,
    specifications: {
      fav: "NVIDIA GeForce RTX 2060",
      processor: "Intel Core i5-9300H",
      memory: "16GB DDR4",
      storage: "512GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce RTX 2060",
      screen: "15.6 polegadas Full HD",
      weight: "2.5 Kg",
    },
  },
  {
    id: 2,
    name: "Notebook Gamer Dell G5",
    description:
      "O Dell G5 oferece uma experiência de jogo fluida e gráficos de alta qualidade.",
    brand: "Dell",
    model: "G5-5590-A30B",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fdell-g5.png?alt=media&token=ac1cb3fa-4cc4-4f30-a831-19bca5b85644",
    videoReview:
      "https://www.youtube.com/embed/N5C1ALQkv1Q?si=KuVr4V6-A02Z23XK",
    rate: 5,
    tags: [],
    basePrice: 7299.99,
    promotionPrice: 6799.99,
    smallPrice: 4850,
    mediumPrice: 6500,
    largePrice: 9800,
    specifications: {
      fav: "NVIDIA GeForce GTX 1660 Ti",
      processor: "Intel Core i7-9750H",
      memory: "16GB DDR4",
      storage: "1TB HDD + 256GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce GTX 1660 Ti",
      screen: "15.6 polegadas Full HD",
      weight: "2.68 Kg",
    },
  },
  {
    id: 3,
    name: "Notebook Gamer Lenovo Legion Y540",
    description:
      "O Lenovo Legion Y540 é um notebook gamer de alta performance com design elegante.",
    brand: "Lenovo",
    model: "Legion Y540-15IRH",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Flegion-y540.png?alt=media&token=b36f6c61-8b7d-4454-9940-d945b89d44f8",
    videoReview:
      "https://www.youtube.com/embed/knhriyVTMpA?si=3RduZcEVx4mjEwER",
    rate: 4.5,
    tags: ["Recomendado"],
    basePrice: 6999.99,
    promotionPrice: 6499.99,
    smallPrice: 4850,
    mediumPrice: 6500,
    largePrice: 9800,
    specifications: {
      fav: "NVIDIA GeForce GTX 1660 Ti",
      processor: "Intel Core i7-9750H",
      memory: "16GB DDR4",
      storage: "512GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce GTX 1660 Ti",
      screen: "15.6 polegadas Full HD",
      weight: "2.3 Kg",
    },
  },
  {
    id: 4,
    name: "Notebook Gamer HP Pavilion",
    description:
      "O HP Pavilion é um notebook gamer com desempenho sólido e design moderno, perfeito para jogadores que buscam custo-benefício.",
    brand: "HP",
    model: "Pavilion 15-dk0010",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fhp-pavilion-dk0010.png?alt=media&token=6f0d7c8d-0612-4ca9-9ee8-1849971ae8c4",
    videoReview:
      "https://www.youtube.com/embed/dCvvugSjnZ4?si=zOMGbydgNdkB9QwY",
    rate: 4,
    tags: [],
    basePrice: 5499.99,
    promotionPrice: 4999.99,
    smallPrice: 4133,
    mediumPrice: 5107.9,
    largePrice: 7990.9,
    specifications: {
      fav: "NVIDIA GeForce GTX 1650",
      processor: "Intel Core i5-9300H",
      memory: "8GB DDR4",
      storage: "256GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce GTX 1650",
      screen: "15.6 polegadas Full HD",
      weight: "2.25 Kg",
    },
  },
  {
    id: 5,
    name: "Notebook Gamer ASUS TUF A15",
    description:
      "O ASUS TUF Gaming A15 combina durabilidade militar com um desempenho excelente para jogos.",
    brand: "ASUS",
    model: "TUF A15 FA506IV",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fasus-tuf-a15.png?alt=media&token=989d3375-f26b-4ada-a920-afa41dfdb8de",
    videoReview:
      "https://www.youtube.com/embed/v-LmH_Gfnn8?si=IGQmsvb-eZyDInwV",
    rate: 5,
    tags: ["Oportunidade"],
    basePrice: 7499.99,
    promotionPrice: 6999.99,
    smallPrice: 4133,
    mediumPrice: 5107.9,
    largePrice: 7990.9,
    specifications: {
      fav: "NVIDIA GeForce RTX 2060",
      processor: "AMD Ryzen 7 4800H",
      memory: "16GB DDR4",
      storage: "512GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce RTX 2060",
      screen: "15.6 polegadas Full HD 144Hz",
      weight: "2.3 Kg",
    },
  },
  {
    id: 6,
    name: "Notebook Gamer MSI GL65 Leopard",
    description:
      "O MSI GL65 Leopard oferece um desempenho superior com design agressivo e teclado RGB personalizável.",
    brand: "MSI",
    model: "GL65 Leopard 10SFK-062",
    image:
      "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmsi-gl65.png?alt=media&token=24798828-8546-4720-bfe7-f813f4e78507",
    videoReview:
      "https://www.youtube.com/embed/uT-YHREKDaE?si=Z7e2lk9G-H7-cghs",
    rate: 4,
    tags: ["Melhor RTX 2070"],
    basePrice: 8999.99,
    promotionPrice: 8499.99,
    smallPrice: 4133,
    mediumPrice: 5107.9,
    largePrice: 7990.9,
    specifications: {
      fav: "NVIDIA GeForce RTX 2070",
      processor: "Intel Core i7-10750H",
      memory: "16GB DDR4",
      storage: "512GB SSD",
      "Placa de Vídeo": "NVIDIA GeForce RTX 2070",
      screen: "15.6 polegadas Full HD 144Hz",
      weight: "2.3 Kg",
    },
  },
  {
    id: 7,
    name: 'Razer Blade 15 Gaming Laptop',
    description:
        'The Razer Blade 15 is a premium gaming laptop with a sleek design and top-notch hardware.',
    brand: 'Razer',
    model: 'Blade 15 Base',
    image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Frazer-blade-15.png?alt=media&token=6e23866d-56d0-4da9-94e8-feb1b57d8fac',
    rate: 5,
    videoReview: 'https://www.youtube.com/embed/7kpreUxmHvA?si=wj5A9bw4F8zm_w_Y',
    tags: [],
    basePrice: 12499.99,
    promotionPrice: 11999.99,
    smallPrice: 6850,
    largePrice: 13500,
    mediumPrice: 10900.9,
    specifications: {
        fav: 'NVIDIA GeForce RTX 2070',
        processor: 'Intel Core i7-10750H',
        memory: '16GB DDR4',
        storage: '512GB SSD',
        videoCard: 'NVIDIA GeForce RTX 2070',
        screen: '15.6 inch Full HD 144Hz',
        weight: '2.1 Kg',
    },
},
{
    id: 8,
    name: 'Alienware m15 Gaming Laptop',
    description:
        'The Alienware m15 is a high-performance gaming laptop with a futuristic design and advanced features.',
    brand: 'Dell',
    model: 'm15 R3',
    image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Falienware-m15.png?alt=media&token=85df89d1-3db1-4978-9581-4802b42d7c6e',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/OywbZPwHJBw?si=cZmqJESmXGh-D1Bw',
    tags: ['No Interest'],
    basePrice: 14999.99,
    promotionPrice: 13999.99,
    smallPrice: 4133,
    largePrice: 7990.9,
    mediumPrice: 5107.9,
    specifications: {
        fav: 'NVIDIA GeForce RTX 2080 Super',
        processor: 'Intel Core i7-10875H',
        memory: '16GB DDR4',
        storage: '1TB SSD',
        videoCard: 'NVIDIA GeForce RTX 2080 Super',
        screen: '15.6 inch Full HD 240Hz',
        weight: '2.5 Kg',
    },
},
{
    id: 9,
    name: 'AMD Ryzen 7 5700X3D Processor',
    description:
        'Enjoy supersonic speeds with 8 cores and 16 threads of processing, ready to tackle the most challenging titles. Base frequency of 3.0GHz and dynamic boost up to 4.1GHz to eliminate any stuttering.',
    brand: 'AMD',
    model: '100-100001503WOF',
    image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fryzen-7-5700x3d.png?alt=media&token=62caf240-b3c6-41d9-889a-c4ca882822d9',
    rate: 4.5,
    videoReview: 'https://www.youtube.com/embed/ic8a_L15Z98&t=67s',
    tags: ['No Interest', 'Best Sellers', 'Value for Money'],
    basePrice: 2499.99,
    promotionPrice: 1189.99,
    smallPrice: 999.99,
    largePrice: 3290.9,
    mediumPrice: 1699.9,
    specifications: {
        fav: 'AMD Ryzen 7 5700X3D',
        cpuCores: 8,
        cpuThreads: 16,
        maxBoostClock: 4.1,
        baseClock: 3.0,
        totalL2Cache: '4MB',
        totalL3Cache: '96MB',
        socket: 'AM4',
        maxTemperature: '90°C',
        weight: '243 g',
    },
},
{
    id: 10,
    name: 'Intel Core i9-13900K Processor',
    description:
        'The Intel Core i9-13900K is the ideal processor for gamers and professionals who need extreme performance. Equipped with 24 cores and 32 threads, it reaches frequencies of up to 5.8 GHz in turbo mode, delivering unparalleled performance.',
    brand: 'Intel',
    model: 'BX8071513900K',
    image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fcore-i9-13900k.png?alt=media&token=9d185bf6-64ca-48bf-bdb7-acd0de317f09',
    rate: 4.8,
    videoReview: 'https://www.youtube.com/embed/tV-FbmLJejg',
    tags: ['Maximum Performance', 'Recommended for Gaming', 'Overclock'],
    basePrice: 3899.99,
    promotionPrice: 3299.99,
    smallPrice: 2999.99,
    largePrice: 4199.9,
    mediumPrice: 3599.9,
    specifications: {
        fav: 'Intel Core i9-13900K',
        cpuCores: 24,
        cpuThreads: 32,
        maxBoostClock: 5.8,
        baseClock: 3.0,
        totalL2Cache: '32 MB',
        totalL3Cache: '36 MB',
        socket: 'LGA 1700',
        weight: '101 g',
    },
},
  
];

export default products;
